#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Wed Aug 13 23:15:38 2014

import wx
import pygame
import time


# begin wxGlade: extracode
# end wxGlade



import sqlite3 as mysql
import os,sys


dir = os.path.split(sys.argv[0])[0]
Mydb=dir+'/poll.db'


if os.path.exists(Mydb):
    
    #pass
    print "eixts",Mydb
    
else:
    
    print "DB not existin"
    
print dir



class voting_machine(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__ wx.CAPTION | wx.MINIMIZE_BOX   |wx.RESIZE_BORDER| |wx.STAY_ON_TOP
        #kwds["style"] =wx.CLIP_CHILDREN| wx.MAXIMIZE|wx.SYSTEM_MENU|wx.NO_BORDER|wx.STAY_ON_TOP
        """kwds["style"] =wx.DEFAULT_FRAME_STYLE & ~ (wx.RESIZE_BORDER | 
                                                wx.RESIZE_BOX | 
                                                wx.MAXIMIZE_BOX)
        """
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.ScrolledWindow(self, -1, style=wx.TAB_TRAVERSAL)
        self.bitmap_button_1 = wx.BitmapButton(self.panel_1, -1, wx.Bitmap(dir+"/images/green.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_2 = wx.BitmapButton(self.panel_1, -1, wx.Bitmap(dir+"/images/red.png", wx.BITMAP_TYPE_ANY))
        self.label_1 = wx.StaticText(self.panel_1, -1, "1")
        self.label_2 = wx.StaticText(self.panel_1, -1, "2")
        self.label_3 = wx.StaticText(self.panel_1, -1, "3")
        self.label_4 = wx.StaticText(self.panel_1, -1, "4")
        self.label_5 = wx.StaticText(self.panel_1, -1, "5")
        self.button_1 = wx.Button(self.panel_1, -1, "", style=wx.BU_EXACTFIT)
        self.button_3 = wx.Button(self.panel_1, -1, "", style=wx.BU_EXACTFIT)
        self.button_5 = wx.Button(self.panel_1, -1, "", style=wx.BU_EXACTFIT)
        self.button_7 = wx.Button(self.panel_1, -1, "", style=wx.BU_EXACTFIT)
        self.button_9 = wx.Button(self.panel_1, -1, "", style=wx.BU_EXACTFIT)
        self.label_6 = wx.StaticText(self.panel_1, -1, "6")
        self.label_7 = wx.StaticText(self.panel_1, -1, "7")
        self.label_8 = wx.StaticText(self.panel_1, -1, "8")
        self.label_9 = wx.StaticText(self.panel_1, -1, "9")
        self.label_10 = wx.StaticText(self.panel_1, -1, "10")
        self.button_2 = wx.Button(self.panel_1, -1, "", style=wx.BU_EXACTFIT)
        self.button_4 = wx.Button(self.panel_1, -1, "", style=wx.BU_EXACTFIT)
        self.button_6 = wx.Button(self.panel_1, -1, "", style=wx.BU_EXACTFIT)
        self.button_8 = wx.Button(self.panel_1, -1, "", style=wx.BU_EXACTFIT)
        self.button_10 = wx.Button(self.panel_1, -1, "", style=wx.BU_EXACTFIT)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnBtn1, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.OnBtn3, self.button_3)
        self.Bind(wx.EVT_BUTTON, self.OnBtn5, self.button_5)
        self.Bind(wx.EVT_BUTTON, self.OnBtn7, self.button_7)
        self.Bind(wx.EVT_BUTTON, self.OnBtn9, self.button_9)
        self.Bind(wx.EVT_BUTTON, self.OnBtn2, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.OnBtn4, self.button_4)
        self.Bind(wx.EVT_BUTTON, self.OnBtn6, self.button_6)
        self.Bind(wx.EVT_BUTTON, self.OnBtn8, self.button_8)
        self.Bind(wx.EVT_BUTTON, self.OnBtn10, self.button_10)
        
        
        self.Bind(wx.EVT_KEY_DOWN, self.OnKeyPress)
        self.button_1.Bind(wx.EVT_KEY_DOWN, self.OnKeyPress)
        self.button_2.Bind(wx.EVT_KEY_DOWN, self.OnKeyPress)
        self.button_3.Bind(wx.EVT_KEY_DOWN, self.OnKeyPress)
        self.button_4.Bind(wx.EVT_KEY_DOWN, self.OnKeyPress)
        self.button_5.Bind(wx.EVT_KEY_DOWN, self.OnKeyPress)
        self.button_6.Bind(wx.EVT_KEY_DOWN, self.OnKeyPress)
        self.button_7.Bind(wx.EVT_KEY_DOWN, self.OnKeyPress)
        self.button_8.Bind(wx.EVT_KEY_DOWN, self.OnKeyPress)
        self.button_9.Bind(wx.EVT_KEY_DOWN, self.OnKeyPress)
        self.button_10.Bind(wx.EVT_KEY_DOWN, self.OnKeyPress)
        
        self.panel_1.Bind(wx.EVT_KEY_DOWN, self.OnKeyPress)
        #self.panel_1.Bind(wx.EVT_MOVE, self.OnMouseMove)
        
        self.Bind(wx.EVT_MOVE, self.OnMouseMove)
        
        self.bitmap_button_1.Bind(wx.EVT_KEY_DOWN, self.OnKeyPress)
        self.bitmap_button_2.Bind(wx.EVT_KEY_DOWN, self.OnKeyPress)
        
        self.Bind(wx.EVT_CLOSE,self.OnClose,self)
        
        
        #self.bitmap_button_1.Bind(wx.EVT_ENTER_WINDOW, self.OnEnterWindow)
        #self.bitmap_button_1.Bind(wx.EVT_LEAVE_WINDOW, self.OnLeaveWindow)
        
        #self.button_1.Bind(wx.EVT_KEY_UP, self.OnKeyUp)
        self.bitmap_button_1.SetFocus()
        self.IsEnabled=True
        
        self.con=mysql.connect(Mydb)
        self.cur = self.con.cursor()
        self.count=0
        self.candidate_buttons=[self.button_1, self.button_2, self.button_3,self.button_4,self.button_5,self.button_6,self.button_7, self.button_8,self.button_9,self.button_10]
           
        self.set_cursor()
        
        self.Maximize(True)
        self.ShowFullScreen(True)
     
        
        
        # end wxGlade
    def set_cursor(self):
        
        cursor = wx.StockCursor(wx.CURSOR_HAND)
        
        for button in self.candidate_buttons: # Changes mouse cursor
                
                
                button.SetCursor(cursor)
    
    def OnClose(self,event):
        self.Parent.Show()
        event.Skip()
    def OnEnterWindow(self,event):
        pass
    def OnLeaveWindow(self,event):
        pass
    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetFocus()
        self.bitmap_button_1.SetSize(self.bitmap_button_1.GetBestSize())
        self.bitmap_button_2.Hide()
        self.bitmap_button_2.SetSize(self.bitmap_button_2.GetBestSize())
        self.label_1.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_1.Hide()
        self.label_2.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_2.Hide()
        self.label_3.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_3.Hide()
        self.label_4.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_4.Hide()
        self.label_5.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_5.Hide()
        self.button_1.SetMinSize((450, 100))
        self.button_1.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.button_1.SetFocus()
        #self.bitmap_button_1.Hide()
        self.button_3.SetMinSize((450, 100))
        self.button_3.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.button_3.SetFocus()
        self.button_3.Hide()
        self.button_5.SetMinSize((450, 100))
        self.button_5.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.button_5.SetFocus()
        self.button_5.Hide()
        self.button_7.SetMinSize((450, 100))
        self.button_7.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.button_7.SetFocus()
        self.button_7.Hide()
        self.button_9.SetMinSize((450, 100))
        self.button_9.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.button_9.SetFocus()
        self.button_9.Hide()
        self.label_6.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_6.Hide()
        self.label_7.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_7.Hide()
        self.label_8.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_8.Hide()
        self.label_9.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_9.Hide()
        self.label_10.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_10.Hide()
        self.button_2.SetMinSize((450, 100))
        self.button_2.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.button_2.SetFocus()
        self.button_2.Hide()
        self.button_4.SetMinSize((450, 100))
        self.button_4.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.button_4.SetFocus()
        self.button_4.Hide()
        self.button_6.SetMinSize((450, 100))
        self.button_6.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.button_6.SetFocus()
        self.button_6.Hide()
        self.button_8.SetMinSize((450, 100))
        self.button_8.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.button_8.SetFocus()
        self.button_8.Hide()
        self.button_10.SetMinSize((450, 100))
        self.button_10.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.button_10.SetFocus()
        self.button_10.Hide()
        #self.panel_1.SetMinSize((768, 692))
        self.panel_1.SetScrollRate(10, 10)
        # end wxGlade



    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_2 = wx.GridSizer(5, 1, 0, 0)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.GridSizer(5, 1, 0, 0)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(self.bitmap_button_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_8.Add(self.bitmap_button_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(sizer_8, 0, wx.EXPAND, 0)
        sizer_6.Add(self.label_1, 0, wx.TOP, 40)
        sizer_6.Add(self.label_2, 0, wx.TOP, 120)
        sizer_6.Add(self.label_3, 0, wx.TOP, 120)
        sizer_6.Add(self.label_4, 0, wx.TOP, 120)
        sizer_6.Add(self.label_5, 0, wx.TOP, 120)
        sizer_4.Add(sizer_6, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.button_1, 0, 0, 0)
        grid_sizer_1.Add(self.button_3, 0, 0, 0)
        grid_sizer_1.Add(self.button_5, 0, 0, 0)
        grid_sizer_1.Add(self.button_7, 0, 0, 0)
        grid_sizer_1.Add(self.button_9, 0, 0, 0)
        sizer_4.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_7.Add(self.label_6, 0, wx.TOP, 40)
        sizer_7.Add(self.label_7, 0, wx.TOP, 120)
        sizer_7.Add(self.label_8, 0, wx.TOP, 120)
        sizer_7.Add(self.label_9, 0, wx.TOP, 120)
        sizer_7.Add(self.label_10, 0, wx.TOP, 120)
        sizer_5.Add(sizer_7, 0, wx.EXPAND, 0)
        grid_sizer_2.Add(self.button_2, 0, 0, 0)
        grid_sizer_2.Add(self.button_4, 0, 0, 0)
        grid_sizer_2.Add(self.button_6, 0, 0, 0)
        grid_sizer_2.Add(self.button_8, 0, 0, 0)
        grid_sizer_2.Add(self.button_10, 0, 0, 0)
        sizer_5.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.TOP | wx.EXPAND, 10)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.ALL | wx.EXPAND, 10)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        self.Centre()
        
        # end wxGlade
        # end wxGlade

    def OnBtn1(self, event):  # wxGlade: MyFrame.<event_handler>
        i=0
        
        self.Save_Vote(i)
        event.Skip()
        
    def OnBtn2(self, event):  # wxGlade: MyFrame.<event_handler>
        
        i=1
        
        self.Save_Vote(i)
        event.Skip()
    
    
    def OnBtn3(self, event):  # wxGlade: MyFrame.<event_handler>
        i=2
        
        self.Save_Vote(i)
        event.Skip()


    def OnBtn4(self, event):  # wxGlade: MyFrame.<event_handler>
        
        
        
        i=3
        
        self.Save_Vote(i)
        event.Skip()


    def OnBtn5(self, event):  # wxGlade: MyFrame.<event_handler>
        i=4
        
        self.Save_Vote(i)
        event.Skip()

    
    

    

    def OnBtn6(self, event):  # wxGlade: MyFrame.<event_handler>
        i=5
        
        self.Save_Vote(i)
        event.Skip()

    def OnBtn7(self, event):  # wxGlade: MyFrame.<event_handler>
        
        i=6
        
        self.Save_Vote(i)
        event.Skip()





    def OnBtn8(self, event):  # wxGlade: MyFrame.<event_handler>
        i=7
        
        self.Save_Vote(i)
        event.Skip()

    def OnBtn9(self, event):  # wxGlade: MyFrame.<event_handler>
        i=8
        
        self.Save_Vote(i)
        event.Skip()

    def OnBtn10(self, event):  # wxGlade: MyFrame.<event_handler>
        i=9
        
        self.Save_Vote(i)
        event.Skip()
    def OnMouseMove(self,e):
        
        
        pass
        '''
        cursor = wx.StockCursor(wx.CURSOR_HAND)
        
        for button in self.candidate_buttons: # Changes mouse cursor                
                
            button.SetCursor(cursor)
            print "changed mouse"
       
        '''
       
    def Save_Vote(self,button_index):
        i=button_index
        
        id=str(self.LIST[i][0])
        cand=str(self.LIST[i][1])
        
        
        query='SELECT VOTE FROM poll WHERE ID=? AND STD=? AND DIV=?'
        self.cur.execute(query,(id,self.CLASS,self.DIV))
        
        try:
            vote=self.cur.fetchone()[0]
            vote=int(vote)
        except:
            vote=0
        
        query='UPDATE poll SET VOTE=? WHERE ID=? AND STD=? AND DIV=?'
        self.cur.execute(query,(vote+1,id,self.CLASS,self.DIV))
        self.con.commit()
        self.Disable()
       
        
        
    
    def Disable(self):
        
        #cursor = wx.StockCursor(wx.CURSOR_CROSS)
        if self.IsEnabled==True:
            self.PlayPolled()
            for button in self.candidate_buttons: # Disables all candiadates buttons
                
                button.Enabled=False
                #button.SetCursor(cursor)
           
            self.IsEnabled=False
            self.bitmap_button_1.Hide()
            self.bitmap_button_2.Show()
            self.bitmap_button_2.SetFocus()
            
            


            
            #self.bitmap_button_1.SetBitmap(wx.Bitmap("/home/asif/Desktop/poll/red.png", wx.BITMAP_TYPE_ANY))
            
            #self.Refresh()
    def Enable(self):
        
        if self.IsEnabled==False:
            self.PlayReady()
            for button in self.candidate_buttons: # Enables all candiadates buttons
                button.Enabled=True
            
            self.IsEnabled=True
            self.bitmap_button_2.Hide()
            self.bitmap_button_1.Show()
            
            self.bitmap_button_1.SetFocus()
        
    def OnKeyPress(self, event):
        keycode = event.GetKeyCode()
       
        #print keycode
        if keycode == wx.WXK_SPACE :
            self.Enable()
            
        elif event.ControlDown() and keycode==69:
            
            self.Close()
            print "closing panel"
        self.SetFocus()
        self.up=0
        event.Skip()
    
        
    def OnKeyUp(self,event):
        #print 'keyup'
        self.up=1
        
    def PlayReady(self):
        
        pygame.init()

        pygame.mixer.music.load(dir+"/ready.mp3")

        pygame.mixer.music.play()

        time.sleep(1)
        
    def PlayPolled(self):
        
        pygame.init()

        pygame.mixer.music.load(dir+"/polled.wav")

        pygame.mixer.music.play()

        time.sleep(1)
        
    def Load(self,std,div):
        
        self.LIST=[]
        self.CLASS=std
        self.DIV=div
       
        query='SELECT ID, CANDIDATE FROM poll WHERE STD=? AND DIV=?'
        self.cur.execute(query,(self.CLASS,self.DIV))
        i=0
        self.BUTTS=[self.button_1,self.button_2,self.button_3,self.button_4]
        self.BUTTS+=[self.button_5,self.button_6,self.button_7]
        self.BUTTS+=[self.button_8,self.button_9,self.button_10]
        
        
        for item in self.cur.fetchall():
            
            self.LIST.append([item[0],item[1]])
            try:
                cand=str(item[1])
                if len(cand)>28:
                    self.BUTTS[i].SetFont(wx.Font(11, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
                self.BUTTS[i].SetLabel(cand)
                self.BUTTS[i].Show()
                
            
            except:
                pass
            
            if i==9:
                break
            i+=1
        self.Maximize(True)
        self.Show()
        

# end of class MyFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = voting_machine(None, -1, "")
    
    
    
    frame_1.Load('8','A')
    app.SetTopWindow(frame_1)
    app.MainLoop()
